### ISSUE TITLE
vmv.s.x and vfmv.f.s seems not support?

### ISSUE THREAD

**Issue by rednoah91** [romanheros/qemu#1]
Hi,

I encountered illegal instructions when program executed `vmv.s.x` and `vfmv.f.s`

[ELF]
https://drive.google.com/open?id=15P7E_xRV5-d82MlabC9emD_LrQPMzhq8

[How to reproduce]
qemu-riscv64 -cpu rv64,x-v=true,vlen=128,elen=64,vext_spec=v0.7.1 ./vmv.s.x_illegal.elf

Can you help check this? Thanks

**Comment by romanheros** [comment]
These two elf use v0.8 encodes for vmv.s.x and vfmv.f.s，which is compatibility with v0.7.1.
Currently, QEMU only support v0.7.1.
Perhaps you should use an assembler compatibility with v0.7.1.

**Comment by romanheros** [comment]
> Hi,
> 
> I encountered illegal instructions when program executed `vmv.s.x` and `vfmv.f.s`
> 
> [ELF]
> https://drive.google.com/open?id=15P7E_xRV5-d82MlabC9emD_LrQPMzhq8
> 
> [How to reproduce]
> qemu-riscv64 -cpu rv64,x-v=true,vlen=128,elen=64,vext_spec=v0.7.1 ./vmv.s.x_illegal.elf
> 
> Can you help check this? Thanks

**Comment by romanheros** [comment]
> Hi,
> 
> I encountered illegal instructions when program executed `vmv.s.x` and `vfmv.f.s`
> 
> [ELF]
> https://drive.google.com/open?id=15P7E_xRV5-d82MlabC9emD_LrQPMzhq8
> 
> [How to reproduce]
> qemu-riscv64 -cpu rv64,x-v=true,vlen=128,elen=64,vext_spec=v0.7.1 ./vmv.s.x_illegal.elf
> 
> Can you help check this? Thanks

These two elf use v0.8 encodes for vmv.s.x and vfmv.f.s，which are not compatibility with v0.7.1.
Currently, QEMU only support v0.7.1.
Perhaps you should use an assembler compatibility with v0.7.1.
